-- =============================================================================
--  casos.sql — tablas para las casuísticas del bloque 11
-- =============================================================================
--
--  Tres casuísticas necesitan datos con formas que Northwind no tiene:
--  intervalos que se solapan, altas y bajas con periodos, y sucesos con
--  ráfagas. No se puede pedir prestado a `orders`: un pedido es un instante,
--  no un intervalo.
--
--  REQUISITO: haber cargado antes practica.sql, que crea el esquema.
--
--  USO
--      psql -d northwind -f practica.sql   # el esquema
--      psql -d northwind -f casos.sql      # + las tablas de casuísticas
--
--  Es también su propio botón de reset: empieza por DROP TABLE.
--  Los datos son deterministas: no usa random(), así que las respuestas de
--  los temas son siempre las mismas.
-- =============================================================================

DROP TABLE IF EXISTS practica.log_errores;
DROP TABLE IF EXISTS practica.suscripciones;
DROP TABLE IF EXISTS practica.sesiones;

-- -----------------------------------------------------------------------------
-- 1. Sesiones — intervalos que se solapan
-- -----------------------------------------------------------------------------
-- Conexiones a la aplicación. Sirven para "¿cuál fue el máximo de usuarios
-- simultáneos?" y para fusionar rangos que se tocan.

CREATE TABLE practica.sesiones (
    sesion_id  integer     GENERATED BY DEFAULT AS IDENTITY,
    usuario    varchar(20) NOT NULL,
    inicio     timestamp   NOT NULL,
    fin        timestamp   NOT NULL,
    CONSTRAINT pk_sesiones      PRIMARY KEY (sesion_id),
    CONSTRAINT chk_sesiones_fin CHECK (fin > inicio)
);

INSERT INTO practica.sesiones (usuario, inicio, fin)
SELECT 'user' || lpad(((g * 7) % 12 + 1)::text, 2, '0'),
       TIMESTAMP '2025-03-10 08:00:00' + ((g * 17) % 480) * INTERVAL '1 minute',
       TIMESTAMP '2025-03-10 08:00:00' + ((g * 17) % 480) * INTERVAL '1 minute'
                                       + ((g % 7) * 15 + 10) * INTERVAL '1 minute'
FROM generate_series(1, 60) AS g;

-- -----------------------------------------------------------------------------
-- 2. Suscripciones — altas y bajas, con periodos abiertos
-- -----------------------------------------------------------------------------
-- `baja IS NULL` = sigue activa. Es la forma normal de guardar un histórico
-- de contratos, y obliga a razonar con nulos en los rangos.

CREATE TABLE practica.suscripciones (
    suscripcion_id integer     GENERATED BY DEFAULT AS IDENTITY,
    cliente_id     varchar(5)  NOT NULL,
    plan           varchar(10) NOT NULL,
    alta           date        NOT NULL,
    baja           date,
    CONSTRAINT pk_suscripciones    PRIMARY KEY (suscripcion_id),
    CONSTRAINT fk_susc_cliente     FOREIGN KEY (cliente_id)
                                   REFERENCES practica.clientes (cliente_id),
    CONSTRAINT chk_susc_baja       CHECK (baja IS NULL OR baja > alta),
    CONSTRAINT chk_susc_plan       CHECK (plan IN ('basico','pro','empresa'))
);

INSERT INTO practica.suscripciones (cliente_id, plan, alta, baja)
SELECT cliente_id,
       (ARRAY['basico','pro','empresa'])[(n % 3) + 1],
       DATE '2023-01-01' + ((n * 11) % 500),
       CASE WHEN n % 3 = 0
            THEN DATE '2023-01-01' + ((n * 11) % 500) + ((n % 9) * 40 + 60)
       END
FROM (SELECT cliente_id,
             (row_number() OVER (ORDER BY cliente_id))::int AS n
      FROM practica.clientes) t;

-- -----------------------------------------------------------------------------
-- 3. Registro de errores — sucesos con ráfagas
-- -----------------------------------------------------------------------------
-- La mayoría espaciados, y tres momentos donde se apelotonan. Sirve para
-- detectar clusters: "¿cuándo se nos cayó algo?".

CREATE TABLE practica.log_errores (
    error_id  integer      GENERATED BY DEFAULT AS IDENTITY,
    momento   timestamp    NOT NULL,
    servicio  varchar(20)  NOT NULL,
    mensaje   varchar(100) NOT NULL,
    CONSTRAINT pk_log_errores PRIMARY KEY (error_id)
);

-- ruido de fondo: uno cada ~20 minutos durante 24 h
INSERT INTO practica.log_errores (momento, servicio, mensaje)
SELECT TIMESTAMP '2025-03-10 00:00:00' + (g * 19) * INTERVAL '1 minute',
       (ARRAY['api','web','pagos'])[(g % 3) + 1],
       'timeout al conectar'
FROM generate_series(0, 71) AS g;

-- tres ráfagas: 12 errores en pocos minutos cada una
INSERT INTO practica.log_errores (momento, servicio, mensaje)
SELECT base + (g * 40) * INTERVAL '1 second', 'pagos', 'conexion rechazada'
FROM (VALUES (TIMESTAMP '2025-03-10 03:12:00'),
             (TIMESTAMP '2025-03-10 11:45:00'),
             (TIMESTAMP '2025-03-10 19:03:00')) AS r(base),
     generate_series(0, 11) AS g;

-- -----------------------------------------------------------------------------
-- 4. Comprobación
-- -----------------------------------------------------------------------------

SELECT 'sesiones' AS tabla, count(*) AS filas FROM practica.sesiones
UNION ALL SELECT 'suscripciones', count(*) FROM practica.suscripciones
UNION ALL SELECT 'log_errores',   count(*) FROM practica.log_errores
ORDER BY tabla;
