-- =============================================================================
--  practica.sql — banco de pruebas para DML y DDL
-- =============================================================================
--
--  Northwind sirve para CONSULTAR. Este esquema sirve para ESCRIBIR.
--
--  Crea el esquema `practica` con una copia reducida de Northwind. Ahí puedes
--  hacer INSERT, UPDATE, DELETE, TRUNCATE, ALTER y DROP sin tocar las tablas
--  originales de `public`.
--
--  Las tablas se llaman DISTINTO a las de Northwind a propósito. Si se
--  llamaran igual, un `UPDATE customers` sin cualificar podría caer en
--  `public` y destruir el dataset. Con nombres en español ese error no
--  compila: `clientes` no existe en `public`.
--
--  USO
--      psql -d northwind -f practica.sql
--
--  Es también el botón de reset: vuelve a ejecutarlo cuando quieras empezar
--  de cero. DROP SCHEMA ... CASCADE borra todo lo que hayas creado dentro.
--
--  Después, en tu sesión:
--      SET search_path TO practica, public;
-- =============================================================================

DROP SCHEMA IF EXISTS practica CASCADE;
CREATE SCHEMA practica;

-- -----------------------------------------------------------------------------
-- 1. Tablas
-- -----------------------------------------------------------------------------

CREATE TABLE practica.categorias (
    categoria_id  integer       GENERATED BY DEFAULT AS IDENTITY,
    nombre        varchar(30)   NOT NULL,
    descripcion   text,
    CONSTRAINT pk_categorias     PRIMARY KEY (categoria_id),
    CONSTRAINT uq_categorias_nom UNIQUE (nombre)
);

CREATE TABLE practica.clientes (
    cliente_id  varchar(5)   NOT NULL,
    empresa     varchar(40)  NOT NULL,
    contacto    varchar(30),
    cargo       varchar(30),
    ciudad      varchar(15),
    pais        varchar(15),
    telefono    varchar(24),
    CONSTRAINT pk_clientes PRIMARY KEY (cliente_id)
);

CREATE TABLE practica.productos (
    producto_id    integer        GENERATED BY DEFAULT AS IDENTITY,
    nombre         varchar(40)    NOT NULL,
    categoria_id   integer        NOT NULL,
    precio         numeric(10,2)  NOT NULL DEFAULT 0,
    stock          smallint       NOT NULL DEFAULT 0,
    nivel_reposicion smallint     NOT NULL DEFAULT 0,
    descontinuado  boolean        NOT NULL DEFAULT false,
    CONSTRAINT pk_productos      PRIMARY KEY (producto_id),
    CONSTRAINT fk_productos_cat  FOREIGN KEY (categoria_id)
                                 REFERENCES practica.categorias (categoria_id),
    CONSTRAINT chk_prod_precio   CHECK (precio >= 0),
    CONSTRAINT chk_prod_stock    CHECK (stock  >= 0),
    CONSTRAINT chk_prod_nivel    CHECK (nivel_reposicion >= 0)
);

CREATE TABLE practica.pedidos (
    pedido_id        integer       GENERATED BY DEFAULT AS IDENTITY,
    cliente_id       varchar(5)    NOT NULL,
    empleado_id      integer       NOT NULL,
    fecha_pedido     date          NOT NULL DEFAULT current_date,
    fecha_requerida  date,
    fecha_envio      date,
    flete            numeric(10,2) NOT NULL DEFAULT 0,
    ciudad_envio     varchar(15),
    pais_envio       varchar(15),
    CONSTRAINT pk_pedidos          PRIMARY KEY (pedido_id),
    CONSTRAINT fk_pedidos_clientes FOREIGN KEY (cliente_id)
                                   REFERENCES practica.clientes (cliente_id),
    CONSTRAINT chk_ped_flete       CHECK (flete >= 0),
    CONSTRAINT chk_ped_requerida   CHECK (fecha_requerida >= fecha_pedido),
    CONSTRAINT chk_ped_envio       CHECK (fecha_envio IS NULL
                                          OR fecha_envio >= fecha_pedido)
);

CREATE TABLE practica.detalle_pedidos (
    pedido_id    integer        NOT NULL,
    producto_id  integer        NOT NULL,
    precio       numeric(10,2)  NOT NULL,
    cantidad     smallint       NOT NULL DEFAULT 1,
    descuento    numeric(4,3)   NOT NULL DEFAULT 0,
    CONSTRAINT pk_detalle          PRIMARY KEY (pedido_id, producto_id),
    CONSTRAINT fk_detalle_pedidos  FOREIGN KEY (pedido_id)
                                   REFERENCES practica.pedidos (pedido_id),
    CONSTRAINT fk_detalle_producto FOREIGN KEY (producto_id)
                                   REFERENCES practica.productos (producto_id),
    CONSTRAINT chk_det_precio      CHECK (precio   >= 0),
    CONSTRAINT chk_det_cantidad    CHECK (cantidad >  0),
    CONSTRAINT chk_det_descuento   CHECK (descuento BETWEEN 0 AND 1)
);

-- -----------------------------------------------------------------------------
-- 2. Carga desde Northwind
-- -----------------------------------------------------------------------------

INSERT INTO practica.categorias (categoria_id, nombre, descripcion)
SELECT category_id, category_name, description FROM public.categories;

INSERT INTO practica.clientes (cliente_id, empresa, contacto, cargo, ciudad, pais, telefono)
SELECT customer_id, company_name, contact_name, contact_title, city, country, phone
FROM public.customers;

INSERT INTO practica.productos (producto_id, nombre, categoria_id, precio, stock,
                                nivel_reposicion, descontinuado)
SELECT product_id, product_name, category_id,
       coalesce(unit_price, 0), coalesce(units_in_stock, 0),
       coalesce(reorder_level, 0), discontinued
FROM public.products;

INSERT INTO practica.pedidos (pedido_id, cliente_id, empleado_id, fecha_pedido,
                              fecha_requerida, fecha_envio, flete, ciudad_envio, pais_envio)
SELECT order_id, customer_id, employee_id, order_date,
       required_date, shipped_date, coalesce(freight, 0), ship_city, ship_country
FROM public.orders;

INSERT INTO practica.detalle_pedidos (pedido_id, producto_id, precio, cantidad, descuento)
SELECT order_id, product_id, unit_price, quantity, discount
FROM public.order_details;

-- -----------------------------------------------------------------------------
-- 3. Poner las secuencias por delante de los ids ya cargados
-- -----------------------------------------------------------------------------
-- Sin esto, el primer INSERT sin id choca contra una fila existente.
-- Es el gotcha clásico al migrar datos con ids fijos.

SELECT setval(pg_get_serial_sequence('practica.categorias', 'categoria_id'),
              (SELECT max(categoria_id) FROM practica.categorias));
SELECT setval(pg_get_serial_sequence('practica.productos',  'producto_id'),
              (SELECT max(producto_id)  FROM practica.productos));
SELECT setval(pg_get_serial_sequence('practica.pedidos',    'pedido_id'),
              (SELECT max(pedido_id)    FROM practica.pedidos));

-- -----------------------------------------------------------------------------
-- 4. Comprobación
-- -----------------------------------------------------------------------------

SELECT 'categorias' AS tabla, count(*) AS filas FROM practica.categorias
UNION ALL SELECT 'clientes',        count(*) FROM practica.clientes
UNION ALL SELECT 'productos',       count(*) FROM practica.productos
UNION ALL SELECT 'pedidos',         count(*) FROM practica.pedidos
UNION ALL SELECT 'detalle_pedidos', count(*) FROM practica.detalle_pedidos
ORDER BY tabla;
